AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  TestingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../chocolate-serverless-stack/
      # Handler: dist/lambdas/calculate-and-apply-non-subsidised-return/index.handler
      Handler: dist/lambdas/dev-send-slack-test/index.handler
      Runtime: nodejs16.x
      Architectures:
        - arm64
      Environment:
        Variables:
          SLACK_WEBHOOK_SECRET_ARN: arn:aws:secretsmanager:ap-southeast-1:782242702936:secret:ThirdPartyChannelURLE022BE1-Sghz0WOGjJMr-mZVIYW
      Policies:
        - SecretsManagerAccessPolicy:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: "*"