AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  TestingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../chocolate-serverless-stack/
      Handler: dist/lambdas/calculate-and-apply-non-subsidised-return/index.handler
      Runtime: nodejs14.x
      Architectures:
        - arm64
      Events:
        Testing:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /testing
            Method: get
      Environment:
        Variables:
          IRESS_USERNAME_ARN: arn:aws:secretsmanager:ap-southeast-1:212535165024:secret:IRESS_USERNAME-ShegeD
          IRESS_PASSWORD_ARN: arn:aws:secretsmanager:ap-southeast-1:212535165024:secret:IRESS_PASSWORD-m32gyC
          IRESS_OTP_SECRET_ARN: arn:aws:secretsmanager:ap-southeast-1:212535165024:secret:IRESS_OTP_SECRET-ODWbRs
